name: deploy-sa
on:
  workflow_dispatch:
  
env:
 AZ_RG_NAME: RG6
 AZ_RG_LOCATION: WestEurope

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: sign in to Azure
        uses: azure/login@v1
        with:
          client-id: 
          tenant-id: 
          subscription-id: 

      - name: deploy RG
        uses: azure/cli@v1
        with:
         inlineScript:
          az group create --name ${{env.AZ_RG_NAME}} --location ${{env.AZ_RG_LOCATION}}
          
      - name: deploy storage
        uses: azure/arm-deploy@v1
        with:
         deploymentName: ${{github.run_Number}}
         resourceGroupName: ${{env.AZ_RG_NAME}}
         template: ./sa.bicep
